# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: jansanchez/sqlite-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: hemiron_security